### ISSUE TITLE
Cannot delete ProjectAssessment when it's linked to matriculation exam enrollment

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/pyramus#1050]
Trying to delete a ProjectAssessment that is linked to matriculation exam enrollment gives internal error warning.

Possible solutions:
* Give a warning that it cannot be deleted
* Just delete it and remove the reference silently
* Ask user for approval for the deletion when it's linked (combination of the two above)

**Comment by aviljakaine** [comment]
Marking this as closed with https://github.com/otavanopisto/pyramus/pull/1604 as the ProjectAssessments are not being used for matriculation grades anymore. It doesn't resolve the issues with the old data though, that has to be manually inspected and corrected.
