### ISSUE TITLE
Nationality isn't the same as Citizenship

### ISSUE THREAD

**Issue by myrtti** [otavanopisto/pyramus#110]
When translating the Setup Wizard, I realised that it doesn't make any difference between nationality and citizenship. Although the terms are often used interchangeably, in legal terms in different jurisdictions there can be a difference.

> Nationality is often used as a synonym for citizenship in English[1] – notably in international law – although the term is sometimes understood as denoting a person's membership of a nation.[2]

Example: Navajo nationals, Sami, Roma, Basque...

**Comment by jjlankinen** [comment]
Non issue
