### ISSUE TITLE
Aineopiskelulinjoilla opiskeleville ainevalinnat automaattisesti

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/pyramus#1533]
Kun opiskelija suorittaa kurssin ja opiskelijalla ei ole ainevalintaa, ainevalinta määrittyisi automaattisesti. Tällaisia lukioaineita ovat

- MAA/MAB
- ET/UE/UO
- ÄI/S2
- kaikki kielet (A, B1 ja B3)

→ opiskelija voi opiskella mahdollisesti useampaa lyhyttä kieltä (B3-kielet)

Mietittiin, että onko aineopiskelijalla estettä opiskella esimerkiksi eli valita sekä pitkää että lyhyttä matikkaa. → Onko estettä siis vaikka Kosken näkökulmasta?

Tämä koskee seuraavia aineopiskelulinjoja:

- Aineopiskelu/lukio
- Aineopiskelu/lukio (oppilvelvolliset)
- Aineopiskelu/yo-tutkinto

**Comment by aviljakaine** [comment]
suorittaa => opettaja antaa arvosanan kurssista
