### ISSUE TITLE
Opiskelijan tietoihin uusia kenttiä

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/pyramus#1541]
Slice integraatiota varten tarvitaan opiskelijan tietoihin seuraavat uudet tiedot:

* Korttityyppi (sininen/vihreä/ei korttia)
* Onko opiskelija ottanut kortin käyttöön (kyllä/ei)
* Kortin voimassaoloaika

**Kortin voimassaoloaika** 

Tämä tarkoittaa aikaa mihin asti kortti on voimassa. Tämä tieto ensisijaisesti päätellään opiskelijan opinto-oikeudesta ja ylikirjoitetaan mikäli opinnot päättyvät aikaisemmin opintojen päättymispäivästä. Tämä kentän voi myös ylikirjoittaa paikallisesti riippumatta edellä mainittujen kenttien arvoista.

Järjestys miten voimassaoloaika määräytyy:
Opinto-oikeuden päätymispäivä < opintojen päättymispäivä < kenttään syötetty päivämäärä

**Korttityypit**

Korttityyppejä on kaksi jotka on kuvattu tässä väreillä joka ei ole luonnollisesti järkevä tapa erotella kortteja lopullisessa versiossa. Oletus on _ei korttia_.

**Onko opiskelija ottanut kortin käyttöön (kyllä/ei)**

Tämä tieto voidaan asettaa paikallisesti Pyramuksessa opiskelijan tiedoissa ja/tai synkronoida Muikusta opiskelijan omien tietojen kautta tallennettuna tai opiskelijahakemuksen kautta kerättynä. Kyseinen kenttä määrittää sen onko opiskelija antanut luvan välittää hänen tiedot Slice:lle vai ei. 

Child of #1542

**Comment by aviljakaine** [comment]
Laittaisin mainitut kentät omaan entiteettiin, koska
a. Student:ssa on jo älyttömästi kenttiä + suurimman osan ajasta Slicen muuttujien arvoja ei tarvita Student:ia käsitellessä
b. Muuttujia voisi käyttää, mutta toisaalta oman entiteetin etuna on, että voidaan käyttää esim enum:ia korttityypiksi ja ko. kenttiä käsitellään vain silloin kun niitä on tarkoitus käsitellä (eikä esim "muuttujamassana")

**Comment by aviljakaine** [comment]
Closed in https://github.com/otavanopisto/pyramus/pull/1580
