### ISSUE TITLE
Majoitustiedot Pyramukseen

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/pyramus#209]
_From @anttiviljakainen on September 24, 2015 6:18_

Pyramukseen on pyydetty majoitustietoja kurssilaisiin liittyen. Tarvittavat tiedot:
- Huoneen numero (kurssin opiskelija)
- Huoneen hinta
- Huonetyyppi

Lisätietoja Heliltä

_Copied from original issue: otavanopisto/board#757_

**Comment by anttiviljakainen** [comment]
Done, closed.
