### ISSUE TITLE
Kurssin hinta Pyramukseen

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/pyramus#210]
_From @anttiviljakainen on September 24, 2015 6:18_

Maksullisten kurssien hinta pitäisi pystyä tallentamaan Pyramukseen ja tämä liitettyä kurssin opiskelijaan.

Lisätietoja Heliltä

_Copied from original issue: otavanopisto/board#758_

**Comment by anttiviljakainen** [comment]
Done, closed.
