### ISSUE TITLE
Documentation manual

### ISSUE THREAD

**Issue by macapon** [otavanopisto/pyramus#247]
Does pyramus has a documentation manual and if yes where can i find it?

**Comment by anttileppa** [comment]
Unfortunately manual currently does not exist. Are you asking this just for general curiosity or are you considering to start using Pyramus in your school as a school’s administration system?

**Comment by macapon** [comment]
I am working on an android client to handle all of the REST APIs which is  already in the pyramus. I therefore need a better understanding of how pyramus works. After that I will like to start using Pyramus in my school as a school’s administration system. Thanks

**Comment by anttileppa** [comment]
As i previously said we do not have an user's manual but we are glad to answer any questions you have and hear about your development ideas. 

While Pyramus is in active development we are primarily developing it to our needs but anyone else is free to use it also.
