### ISSUE TITLE
Additional contact information is not saved when editing a student [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#33]
This is [Issue 33](http://code.google.com/p/pyramus/issues/detail?id=33) moved from a Google Code project.
Added by 2011-03-08T09:17:28.000Z by [marjalii...@otavanopisto.fi](http://code.google.com/u/103717621073720661116/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

    <b>What steps will reproduce the problem?</b>
    1. Fill in field Other Contact Information (Muut yhteystiedot)on the Student Information Form. 
    2. Save.
    
    The information wo'nt be saved, so there must be something wrong in the saving operation.

**Comment by anttiviljakainen** [comment]
Seems to save ok now, closed.
