### ISSUE TITLE
Pyramus war undeployment crashesh [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#45]
This is [Issue 45](http://code.google.com/p/pyramus/issues/detail?id=45) moved from a Google Code project.
Added by 2011-04-07T06:18:00.000Z by [antti.le...@otavanopisto.fi](http://code.google.com/u/106558084578713142111/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-High

### Original description

    <b>What steps will reproduce the problem?</b>
    1. Deploy Pyramus war
    2. Undeploy Pyramus war
    
    <b>What is the expected output? What do you see instead?</b>
    
    Undeployment crashes with error code 500 and takes the whole Glassfish along with it.

**Comment by anttiviljakainen** [comment]
Glassfish? Pyramus has been quite a while on JBoss. Closed.
