### ISSUE TITLE
Loading editcourse view causes all course studenst to be updated [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#46]
This is [Issue 46](http://code.google.com/p/pyramus/issues/detail?id=46) moved from a Google Code project.
Added by 2011-04-13T06:18:15.000Z by [antti.le...@otavanopisto.fi](http://code.google.com/u/106558084578713142111/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-High

### Original description

    <b>What steps will reproduce the problem?</b>
    1. Turn hibernate.show_sql on in persistence.xml 
    2. Edit course that contains students
    
    <b>What is the expected output? What do you see instead?</b>
    
    Viewing page has produced update clause for every coursestudent in course.

**Comment by anttiviljakainen** [comment]
Cannot reproduce (deprecated issue?)
