### ISSUE TITLE
Reservation fee

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/pyramus#470]
#### Source

sen kummenpia stooreja nyt kirjoittelematta kysyisin, että voisiko Pyramukseen lisätä sinne kurssilaiseksi lisätyn i-pallukan taakse vielä toisen luukun, jossa kysyttäisiin varausmaksua (toisessa kysytään majoituksen hintaa)?

Majoitusluukku osaa näköjään miinustaakin itsekseen eli taas saataisin näppityötä vähemmäksi, kun voisin laittaa pyramuksen asiakkaan tietoihin majouituksen hinnan ja hänen maksamansa varausmaksun summan ja ohjelma lisäisi kurssimaksuun majoituksen hinnan ja miinustaisi varausmaksun summan, jolloin viimeiselle viivalle kurssikorttiin tulostuisiko tähteelle laskutettava summa.

*Heli Auvinen*

**Comment by anttiviljakainen** [comment]
Raporttiosuus omassa taskissaan. board/#906
