### ISSUE TITLE
Another textfield to student details

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/pyramus#500]
Helin kuvaus tarpeesta:
olisiko mitenkään mahdollista pikapikaa lisätä Pyramukseen sinne kurssilaisten perässä olevaan i-pallukkaan seuraava juttu:

> - siellä voi valita Otavan asuntolan huoneennumeron, joka tulostuu kurssikorttiin - saisiko samaan valikkoon yhden vapaavalintaisen kentän, johon voisi kopsata Uudenkuun huonenumeron ja koodin tai Huvarin huonenumeron, jolloin sekin tulostuisi kurssikorttiin
> 
> Huone 201 / Ovikoodi 44000  (Uudenkuun numerosetti on tällainen)
> 
> 12.6. alkaa YOOJOO-päivät ja mun pitää majoittaa 108 hlöä Uuteenkuuhun käsipelissä ilman avaimia ja tää avittas hitokseen siinä :) Vois tulostaa vaan kaikille kurssikortin avaimeksi.
> 
> Jos ei kohtuuvella onnistu, niin käytän sitten sitä organisaatiokenttää ja tulostan jokaiselle sitten pahvisen avaimen nimikorttien kautta. Mut siinäkin on sitten taas useampia muita työvaiheita ja senkin sitten hävittävät helposti (kurssikortti olis helppo kopsata jos se häviää).

SH: Heli Auvinen

**Comment by ninakurki** [comment]
Nyt meni tämä asia pieleen eli Heli toivoi tässä siis sinne opiskelijan perässä olevaan i-pallukkaan sen Huone-alaspudotusvalikon alle vaikkapa sellaista ei-pakollista tekstikenttää, johon voipi kirjoittaa mitä haluaa. Jos sillä pitää olla otsikko, niin sehän voisi olla vaikka: Muu majoitus

Ilmeisesti olit siis tulkinnut tämän siten, että Huone-alaspudotusvalikkoon pitää lisätä Uusikuu? Ei pitänyt, se on vähän turha siellä.

**Comment by ilmoeuro** [comment]
Uusikuu on lisätty erikseen, ei liity siis tähän tarinaan. Ninan huomautus aiheeton.
