### ISSUE TITLE
Graduation diplomas do not consider student OPS

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/pyramus#517]
> Nyt näyttäisi siltä, että Pyramuksen päättötodistukset (pk ja lukio) ei huomioi opiskelijan OPS - valintaa.

> Päättäreihin tulee vanhojen OPS:n päivämäärät vaikka opiskelijalle olisi valittu OPS2016.

**Comment by ilmoeuro** [comment]
** Report problem, reported in otavanopisto/board
