### ISSUE TITLE
Saving evaluation date

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/pyramus#587]
#### Source

Hei,

en muista, olenko kirjoittanut tästä aiemmin tai onko joku muu, mutta paljon asiasta on puhuttu.

Eli kun ope arvioi kurssin esim. täydennettäväksi 2.9.2017. Opiskelija täydentää ja ope antaa lopullisen arvosanan 15.9.2017, niin jos ope ei itse huomaa käsin muuttaa arviointipäivää, niin arviointi tallentuu päivälle 2.9.2017.

Parasta olisi, että molemmat päivämäärät tallentuisivat, jotta prosessi jäisi talteen. 

Mutta sekin olisi parannus, että viimeisin arviointipäivä tallentuisi.

Ongelmaksi tässä muodostuu muutama asia:

A) aito arviointipäivä jää vääräksi
B) aineopiskelijalle ei tulostu todistusta lainkaan, koska toimisto ottaa "automatic" aina edellisenä päivänä arvioidut todistukset ulos eli järjestelmään jää aukkoja
c) laskutuksia on hankala tarkistaa, kun ope ilmoittaa laskulla eri päivän kuin mitä meillä tallentuneena Pyramukseen

Annukka

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1965

**Comment by jjlankinen** [comment]
This is done.
