### ISSUE TITLE
Search in 'change course module' does not work with curriculum fiilter

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/pyramus#592]
Change course module dialog's search does not use curriculum filter properly as it returns 0 results if any of the curriculums are selected.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2002

#### SH
Nina Kurki

**Comment by anttiviljakainen** [comment]
Fixed previously in https://github.com/otavanopisto/pyramus/commit/f16a3dcc86350a66fab7048b2a4f46f905aa4b75#diff-50f99233513d81e92b3590a01c01cf7e
