### ISSUE TITLE
Autocomplete functionality to current facility selection

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/pyramus#762]
_From @jjlankinen on March 16, 2018 10:35_

When "Aineopiskelija" selects hes/hers current facility/school it should use autocomplete functionality where results are based on a list created in pyramus.

This means that drop down selection will change to text field with autocomplete feature.

_Copied from original issue: otavanopisto/muikku#3914_

**Comment by pkukkon** [comment]
- resolved in #819
