### ISSUE TITLE
"View School" view incomplete [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#83]
This is [Issue 83](http://code.google.com/p/pyramus/issues/detail?id=83) moved from a Google Code project.
Added by 2012-07-06T08:54:39.000Z by [ilmo.e...@otavanopisto.fi](http://code.google.com/u/118017611714759035636/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-UI

### Original description

    <b>What steps will reproduce the problem?</b>
    1. Log in
    2. Type &quot;https://dev.pyramus.fi:8443/settings/viewschool.page?school=41&quot; into address field.
    3. Observe the results
    
    <b>What is the expected output? What do you see instead?</b>
    Only code, name and variables is shown for the school; address information etc. is missing.
    
    <b>Please use labels and text to provide additional information.</b>

**Comment by anttiviljakainen** [comment]
It ain't pretty but it's been done before, closing.
