### ISSUE TITLE
JSON error form crashes [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#84]
This is [Issue 84](http://code.google.com/p/pyramus/issues/detail?id=84) moved from a Google Code project.
Added by 2012-07-11T05:50:24.000Z by [ilmo.e...@otavanopisto.fi](http://code.google.com/u/118017611714759035636/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-UI

### Original description

    <b>What steps will reproduce the problem?</b>
    1. On front page, click &quot;login&quot;
    2. Enter incorrect username and/or password
    3. Wait for error message
    
    <b>What is the expected output? What do you see instead?</b>
    The error message is never shown; instead, the following appears in the error log:
    08:47:49,229 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/].[jsp]] (http--0.0.0.0-8443-2) Servlet.service() for servlet jsp threw exception: javax.el.ELException: Cannot convert undefined of type class java.lang.String to class java.lang.Long
    
    <b>Please use labels and text to provide additional information.</b>

**Comment by anttiviljakainen** [comment]
Seems ok, closed.
