### ISSUE TITLE
Reports show invalid characters [moved]

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#88]
Moved from Google Code. Original issue: https://code.google.com/p/pyramus/issues/detail?id=89

What steps will reproduce the problem?
1. Open "list reports" view
2. Select "Päätös hyväksilukemisesta"
3. Select a school with Scandic characters in name
4. Hit "OK"

What is the expected output? What do you see instead?
The report contains:
Opiskelijalle ??? on hyväksiluettu lukion kurssisuorituksiksi yhteensä 4 kurssia oheisen liitteen mukaisesti. Opintojen suorituspaikka on ollut YlÃ¶jÃ¤rven tyÃ¶vÃ¤enopisto.

It should contain:
Opiskelijalle ??? on hyväksiluettu lukion kurssisuorituksiksi yhteensä 4 kurssia oheisen liitteen mukaisesti. Opintojen suorituspaikka on ollut Ylöjärven työväenopisto.

HINT: The problem is that the name is sent in an UTF-8 encoded URL string, but Pyramus interprets it as Latin-1.

**Comment by anttiviljakainen** [comment]
Old issue, fixed by report redesign, closed.
