### ISSUE TITLE
Variable system for grades

### ISSUE THREAD

**Issue by otavanopisto** [otavanopisto/pyramus#93]
Moved from Google Code. Original issue: https://code.google.com/p/pyramus/issues/detail?id=94

Some functionality (e.g. phenomenon-based studies) rely on additional info given for grades. Please add a system for attaching free-form information to given grades. Similar systems exist for users, students and courses, among others.

**Comment by anttiviljakainen** [comment]
Assuming resolved with CreditVariable at least by description. Reopen if GradeVariables are necessary.
