### ISSUE TITLE
Opiskelutodistus aikuisten perusopetuksen lukutaitovaiheelle

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/pyramus#960]
OPISKELIJAN NIMI (synt. XX.XX.XXXX) opiskelee Otavan Opistossa aikuisten perusopetuksen luku- ja kirjoitusvaiheen  koulutuksessa lukuvuonna 2019-2019. Lukuvuosi alkoi 2.1.2019 ja päättyy 1.6.2019.

#### Lisätietoa Teresalta

**Comment by anttiviljakainen** [comment]
Tehty 16.4.
